Repository wecode-bootcamp-korea/justcode-6-2nd-team7-front, pull requests merged in 2022-09, with the labels that each got.

#4 Modify: index.scss 추가
  package-lock.json
  package.json
  public/index.html
  src/index.scss
  src/styles/theme.js
Labels: 리뷰요청

#5 Add: 메인페이지 대표이미지, 숙소카테고리 링크 추가(아이콘, 텍스트)
  public/images/main/camping.png
  public/images/main/ghestHouse.png
  public/images/main/hanok.png
  public/images/main/hotel.png
  public/images/main/motel.png
  public/images/main/my.png
  public/images/main/pension.png
  public/images/main/sale.png
  src/Router.js
  src/index.scss
  src/pages/main/Main.js
  src/pages/main/Main.styled.js
  src/pages/main/components/MainLink.js
Labels: 리팩토링중

#6 Add: footer UI 완성
  src/Router.js
  src/component/footer/Footer.js
Labels: 리뷰요청

#9 Feature/mypage
  public/index.html
  src/Router.js
  src/pages/Login/KaKaoLogin.js
  src/pages/Login/Login.Styled.js
  src/pages/Login/Login.js
  src/pages/SignUp/SignUp.Styled.js
  src/pages/SignUp/SignUp.js
  src/pages/login/KaKaoLogin.js
  src/pages/login/Login.Styled.js
  src/pages/login/Login.js
  src/pages/mypage/MyPage.Styled.js
  src/pages/mypage/MyPage.js
  src/pages/mypage/components/Coupons.js
  src/pages/mypage/components/My.Styled.js
  src/pages/mypage/components/My.js
  src/pages/mypage/components/MyPages.Styled.js
  src/pages/mypage/components/NoReservation.js
  src/pages/mypage/components/Points.js
  src/pages/mypage/components/Reservation.Styled.js
  src/pages/mypage/components/Reservation.js
  src/pages/signup/PhoneCheck.Styled.js
  src/pages/signup/SignUp.Styled.js
  src/pages/signup/SignUp.js
  src/pages/signup/SignUpPage.Styled.js
  src/pages/signup/SignUpPage.js
Labels: 리팩토링중, 완료

#8 Add: nav 검색UI 구현
  package-lock.json
  package.json
  public/data/nav/recommend.json
  src/component/nav/Nav.js
  src/component/nav/Nav.styled.js
  src/component/nav/components/MyModal.js
  src/component/nav/components/SeachModal.Styled.js
  src/component/nav/components/SearchModal.js
  src/index.scss
Labels: 리팩토링중

#10 Feature/detail page
  package-lock.json
  package.json
  public/data/roomType.json
  public/index.html
  src/Router.js
  src/pages/detailpage/DetailPage.js
  src/pages/detailpage/DetailPage.styled.js
  src/pages/detailpage/components/Information.js
  src/pages/detailpage/components/Review.js
  src/pages/detailpage/components/Room.js
  src/pages/detailpage/components/Room.styled.js
  src/pages/detailpage/components/RoomGuide.js
Labels: 리뷰요청, 리펙토링 완료

#11 Fix: footer 소셜 아이콘 추가완료
  public/images/footer/blog.png
  public/images/footer/facebook.png
  src/component/footer/Footer.js
Labels: 리뷰요청

#16 Fix/sign up
  src/atom.js
  src/pages/signup/PhoneCheck.Styled.js
  src/pages/signup/PhoneCheck.js
  src/pages/signup/SignUp.Styled.js
  src/pages/signup/SignUpPage.Styled.js
  src/pages/signup/SignUpPage.js
  src/pages/signup/Timer.js
Labels: 리뷰요청, 리팩토링중

#17 Fix: main페이지 완성 (숙소아이콘 링크 부분 제외)
  public/images/main/appDown/appStore.png
  public/images/main/appDown/google.png
  public/images/main/icon/camping.png
  public/images/main/icon/ghestHouse.png
  public/images/main/icon/hotel.png
  public/images/main/icon/koreanHouse.png
  public/images/main/icon/motel.png
  public/images/main/icon/mySpace.png
  public/images/main/icon/payBack.png
  public/images/main/icon/pension.png
  public/images/main/main.png
  public/images/main/news/business.png
  public/images/main/news/font.png
  src/pages/main/Main.js
  src/pages/main/components/AppDown.js
  src/pages/main/components/BoxStyle.Styled.js
  src/pages/main/components/Event.js
  src/pages/main/components/EventSlide.js
  src/pages/main/components/MainLink.js
  src/pages/main/components/News.js
Labels: 리뷰요청

#19 Add: 예약페이지 UI 완성
  src/Router.js
  src/pages/mypage/MyPage.js
  src/pages/mypage/components/ReservationList.Styled.js
  src/pages/mypage/components/ReservationList.js
  src/pages/reservation/Reservation.Styled.js
  src/pages/reservation/Reservation.js
  src/pages/reservation/components/Main.Styled.js
  src/pages/reservation/components/Main.js
  src/pages/reservation/components/Sub.js
Labels: 리뷰요청, 리팩토링중

#20 Fix: 메인페이지 숙소아이콘 링크연결
  src/pages/main/components/MainLink.js
Labels: 리뷰요청

#21 Feature/logout
  package-lock.json
  package.json
  src/Router.js
  src/atom.js
  src/component/modal/LogoutModal.js
  src/component/nav/Nav.styled.js
  src/pages/login/KaKaoLogin.js
  src/pages/login/Login.Styled.js
  src/pages/login/Login.js
  src/pages/mypage/components/My.js
  src/pages/signup/SignUpPage.js
Labels: 리뷰요청

#23 Fix: nav 검색창 입력값 recoil로 state관리, 검색페이지 추가적으로 필요한 UI 완성
  src/Router.js
  src/atom.js
  src/component/nav/Nav.js
  src/component/nav/Nav.styled.js
  src/component/nav/components/MyModal.js
  src/component/nav/components/SeachModal.Styled.js
  src/component/nav/components/SearchModal.js
  src/pages/search/Search.js
Labels: 리팩토링중

#26 Add: 상세페이지이미지슬라이드구현 완료
  .vscode/settings.json
  package-lock.json
  package.json
  public/data/detail/roomType.json
  src/Router.js
  src/pages/detail/Detail.js
  src/pages/detail/Detail.styled.js
  src/pages/detail/components/EventModal.js
  src/pages/detail/components/Information.js
  src/pages/detail/components/Review.js
  src/pages/detail/components/Room.js
  src/pages/detail/components/Room.styled.js
  src/pages/detail/components/RoomGuide.js
  src/pages/detail/components/Slide.js
  src/pages/detail/components/Slide.styled.js
  src/pages/detail/components/SubjectSlide.js
  src/pages/detail/components/SubjectSlide.styled.js
  src/pages/detail/components/UseModal.js
  src/pages/detailpage/DetailPage.js
  src/pages/detailpage/DetailPage.styled.js
  src/pages/detailpage/components/Information.js
  src/pages/detailpage/components/Review.js
  src/pages/detailpage/components/Room.js
  src/pages/detailpage/components/Room.styled.js
  src/pages/detailpage/components/RoomGuide.js
Labels: 완료

#25 Modify: 스타일 수정
  public/data/accommodation/accommodation.json
  public/data/accommodation/accommodationNoData.json
  src/Router.js
  src/atom.js
  src/component/topbutton/TopButton.js
  src/pages/accommodation/AccommodationList.js
  src/pages/accommodation/AccommodationList.styled.js
  src/pages/accommodation/components/Calendar.js
  src/pages/accommodation/components/CheckItem.js
  src/pages/accommodation/components/NoData.js
  src/pages/accommodation/components/SideFilter.js
  src/pages/accommodation/components/ThumbnailList.js
  src/pages/accommodation/components/TopFilter.js
  src/pages/accommodation/components/TopFilter.styled.js
  src/pages/accommodation/data/functions.js
  src/pages/accommodation/data/options.js
  src/pages/signup/PhoneCheck.Styled.js
  src/pages/signup/PhoneCheck.js
  src/pages/signup/SignUp.Styled.js
  src/pages/signup/SignUpPage.Styled.js
Labels: 리펙토링 완료

#27 Fix/kakao login
  .gitignore
  package-lock.json
  src/pages/login/KaKaoLogin.js
  src/pages/login/Login.Styled.js
  src/pages/login/Login.js
  src/pages/signup/SignUpPage.Styled.js
  src/pages/signup/SignUpPage.js
Labels: 리뷰요청

#28 Feature/detail map
  public/data/detail/notice.json
  public/data/detail/review.json
  public/data/detail/roomType.json
  public/data/roomType.json
  src/pages/detail/Detail.js
  src/pages/detail/components/AccommdationInfo.js
  src/pages/detail/components/Information.js
  src/pages/detail/components/map.js
Labels: 완료

#31 Fix: nav 관련된 전반적인 사항 수정
  src/Router.js
  src/component/modal/LogoutModal.js
  src/component/nav/Nav.js
  src/component/nav/Nav.styled.js
  src/component/nav/components/EmptyInputModal.js
  src/component/nav/components/MyModal.js
  src/component/nav/components/SearchModal.js
  src/pages/mypage/components/My.js
  src/pages/search/Search.js
Labels: 리뷰요청

#34 Add: 예약페이지 내정보, 포인트정보 get api
  public/data/my/point.json
  public/data/my/userInfo.json
  src/atom.js
  src/pages/reservation/components/Main.js
Labels: 리뷰요청, 리펙토링 완료

#33 Fix: 오류수정
  src/pages/detail/components/AccommdationInfo.js
  src/pages/detail/components/Information.js
Labels: 리뷰요청, 리팩토링중

#37 Add: 예약할 호텔이름, 객실이름, 총 가격 state 관리 및 상세페이지 css 수정
  package-lock.json
  src/atom.js
  src/pages/detail/Detail.js
  src/pages/detail/components/Room.js
  src/pages/detail/components/Room.styled.js
  src/pages/reservation/components/Main.js
  src/pages/reservation/components/Sub.js
Labels: 리뷰요청

#40 Feature/detail review
  package-lock.json
  package.json
  public/data/detail/review.json
  public/data/detail/roomType.json
  public/images/detail/star.png
  src/pages/detail/Detail.js
  src/pages/detail/components/Review.js
  src/pages/detail/components/ReviewContainer.js
  src/pages/detail/components/ReviewContainer.stlyed.js
Labels: 완료

#41 Fix: 검색창 api 삭제, 검색페이지 api 수정, 검색관련 리코일상태 삭제
  src/Router.js
  src/atom.js
  src/component/nav/Nav.js
  src/component/nav/components/EmptyInputModal.js
  src/component/nav/components/SearchModal.js
  src/pages/detail/components/ReviewContainer.js
  src/pages/search/Search.js
Labels: 리뷰요청

#43 Add: 디테일 페이지 Link 추가
  src/atom.js
  src/pages/accommodation/AccommodationList.js
  src/pages/accommodation/components/CheckItem.js
  src/pages/accommodation/components/NoData.js
  src/pages/accommodation/components/OptionList.js
  src/pages/accommodation/components/SideFilter.js
  src/pages/accommodation/components/Thumbnail.js
  src/pages/accommodation/data/functions.js
  src/pages/accommodation/data/options.js
Labels: 리뷰요청

#44 Add: 임시 API
  src/pages/detail/Detail.js
  src/pages/detail/components/Review.js
  src/pages/detail/components/ReviewContainer.js
  src/pages/detail/components/SubjectSlide.js
Labels: 리뷰요청

#45 Fix: 날짜 설정 시 컴포넌트의 예약버튼 총 금액, 숙박일수 변경
  src/pages/accommodation/components/SideFilter.js
  src/pages/detail/components/Room.js
  src/pages/reservation/components/Sub.js
Labels: 리뷰요청

#46 Modify: 파비콘 경로수정, nav 스마일아이콘 추가, footer 이미지 경로수정
  public/images/Favicon.svg
  public/images/favicon.svg
  public/images/footer/blog.png
  public/images/footer/facebook.png
  public/images/main/icon/hotel.png
  src/component/footer/Footer.js
  src/component/nav/Nav.js
  src/component/nav/Nav.styled.js
  src/component/nav/components/MyModal.js
Labels: 리뷰요청

#47 Add: queryState를 넣은 통신 url 생성
  public/data/accommodation/accommodationNoData.json
  src/pages/accommodation/AccommodationList.js
  src/pages/accommodation/components/Calendar.js
  src/pages/accommodation/components/SideFilter.js
  src/pages/accommodation/components/ThumbnailList.js
Labels: 리뷰요청

#48 Fix: 공통 모달 배경색 theme에 추가, 로그아웃 모달 부분 수정
  src/component/modal/LogoutModal.js
  src/component/nav/components/EmptyInputModal.js
  src/component/nav/components/SeachModal.Styled.js
  src/pages/mypage/components/My.js
  src/styles/theme.js
Labels: 리뷰요청

#49 Add: 검색페이지의 원희님 탑필터, 사이드필터, 썸네일 추가
  src/atom.js
  src/pages/accommodation/components/NoData.js
  src/pages/accommodation/components/SideFilter.js
  src/pages/search/Search.js
Labels: 리뷰요청

#50 Modify: 파일명 오타 수정
  public/data/accomodation/accomodation.json
  public/data/accomodation/accomodationNoData.json
  src/Router.js
  src/pages/accomodation/AccomodationList.js
  src/pages/accomodation/AccomodationList.styled.js
  src/pages/accomodation/components/Calendar.js
  src/pages/accomodation/components/Calendar.styled.js
  src/pages/accomodation/components/CheckItem.js
  src/pages/accomodation/components/CustomSilder.js
  src/pages/accomodation/components/Date.js
  src/pages/accomodation/components/LoadingSpinner.js
  src/pages/accomodation/components/Map.js
  src/pages/accomodation/components/NoData.js
  src/pages/accomodation/components/OptionList.js
  src/pages/accomodation/components/SideFilter.js
  src/pages/accomodation/components/Thumbnail.js
  src/pages/accomodation/components/Thumbnail.styled.js
  src/pages/accomodation/components/TopFilter.js
  src/pages/accomodation/components/TopFilter.styled.js
  src/pages/accomodation/data/check.js
  src/pages/accomodation/data/functions.js
  src/pages/accomodation/data/options.js
  src/pages/accomodation/data/region.js
  src/pages/detail/components/RoomGuide.js
  src/pages/main/components/MainLink.js
  src/pages/search/Search.js
Labels: 완료

#51 Fix: 날짜 선택 시 숙박일수 계산 잘못되던 버그 수정, 예약페이지에서 객실정보 받아오도록 수정
  src/pages/detail/Detail.js
  src/pages/detail/components/Room.js
  src/pages/reservation/components/Main.js
  src/pages/reservation/components/Sub.js
Labels: 리뷰요청

#52 Fix: 예약페이지 내정보, 포인트 get api 수정
  src/pages/reservation/components/Main.js
Labels: 리뷰요청

#53 Modify: 통신하며 코드 수정
  src/pages/accomodation/AccomodationList.js
  src/pages/accomodation/components/CheckItem.js
  src/pages/accomodation/components/Map.js
  src/pages/accomodation/components/OptionList.js
  src/pages/accomodation/components/SideFilter.js
  src/pages/accomodation/data/functions.js
Labels: 리뷰요청

#55 Fix: 예약페이지에서 유효성검사 기준에 따라 생성되는 모달의 내용 변경
  src/pages/reservation/Reservation.js
  src/pages/reservation/components/Main.js
  src/pages/reservation/components/Sub.js
  src/pages/reservation/components/SubmitModal.js
Labels: 리뷰요청

#58 Add: 검색페이지 서버통신 api 완료, 검색창 수정
  src/component/nav/components/SeachModal.Styled.js
  src/component/nav/components/SearchModal.js
  src/pages/accommodation/AccommodationList.js
  src/pages/accommodation/components/Thumbnail.js
  src/pages/search/Search.js
Labels: 리뷰요청

#59 Fix: 초기화버튼 체크박스 초기화 해결
  src/atom.js
  src/pages/accommodation/AccommodationList.js
  src/pages/accommodation/components/Calendar.js
  src/pages/accommodation/components/CheckItem.js
  src/pages/accommodation/components/CustomSilder.js
  src/pages/accommodation/components/Date.js
  src/pages/accommodation/components/Map.js
  src/pages/accommodation/components/OptionList.js
  src/pages/accommodation/components/SideFilter.js
  src/pages/accommodation/data/check.js
  src/pages/accommodation/data/functions.js
  src/pages/accommodation/data/options.js
  src/pages/main/components/MainLink.js
  src/pages/mypage/components/ReservationList.js
Labels: 리뷰요청

#60 Fix/detail api
  public/data/detail/roomType.json
  src/pages/detail/Detail.js
  src/pages/detail/components/Review.js
  src/pages/detail/components/ReviewContainer.js
  src/pages/detail/components/Room.js
  src/pages/detail/components/Slide.styled.js
  src/pages/detail/components/SubjectSlide.js
  src/pages/detail/components/SubjectSlide.styled.js
Labels: 리뷰요청

#61 Fix: 통신하며 최종 점검
  src/pages/accommodation/AccommodationList.js
  src/pages/accommodation/components/SideFilter.js
Labels: 리뷰요청

#62 Modify: 화면 어디서든 로고를 클릭하면 메인화면 맨 위로 올라가는 기능 추가
  src/component/nav/Nav.js
  src/pages/main/components/MainLink.js
Labels: 리뷰요청

#63 Modify: search페이지에서도 queryArr을 이용할 수 있도록 수정
  src/pages/accommodation/components/SideFilter.js
  src/pages/accommodation/data/functions.js
Labels: 리뷰요청

#66 Api test
  src/component/modal/LogoutModal.js
  src/pages/detail/Detail.js
  src/pages/detail/components/Review.js
  src/pages/detail/components/Room.js
  src/pages/main/components/Event.js
  src/pages/reservation/components/Main.js
  src/pages/search/Search.js
Labels: 리뷰요청

#67 Refator/detail
  src/pages/accommodation/data/functions.js
  src/pages/detail/Detail.js
  src/pages/detail/Detail.styled.js
  src/pages/detail/components/Review.js
  src/pages/detail/components/ReviewContainer.js
  src/pages/detail/components/ReviewContainer.stlyed.js
  src/pages/detail/components/Room.js
  src/pages/detail/components/Room.styled.js
  src/pages/detail/components/UseModal.js
Labels: 리뷰요청
